### ISSUE TITLE
What Node version is required

### ISSUE THREAD

**Issue by ale-sanchez-g** [michaelKurowski/gpt-codebase-scanner#1]
I been trying to Run with the below and is not working

V14
V16
V17

**Comment by michaelKurowski** [comment]
I've been using v19.6.0 personally. In case if it won't work, feel free to throw the error at me.

**Comment by ale-sanchez-g** [comment]
@michaelKurowski I am getting this error

```
Parsing codebase...
Creating vector store...
file:///Users/alejandrosanchezgiraldo/git/forks/gpt-codebase-scanner/node_modules/langchain/dist/util/axios-fetch-adapter.js:234
    const headers = new Headers(config.headers);
                    ^

ReferenceError: Headers is not defined
    at createRequest (file:///Users/alejandrosanchezgiraldo/git/forks/gpt-codebase-scanner/node_modules/langchain/dist/util/axios-fetch-adapter.js:234:21)
    at fetchAdapter (file:///Users/alejandrosanchezgiraldo/git/forks/gpt-codebase-scanner/node_modules/langchain/dist/util/axios-fetch-adapter.js:164:21)
    at dispatchRequest (/Users/alejandrosanchezgiraldo/git/forks/gpt-codebase-scanner/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/Users/alejandrosanchezgiraldo/git/forks/gpt-codebase-scanner/node_modules/axios/lib/core/Axios.js:108:15)
    at Function.wrap [as request] (/Users/alejandrosanchezgiraldo/git/forks/gpt-codebase-scanner/node_modules/axios/lib/helpers/bind.js:9:15)
    at /Users/alejandrosanchezgiraldo/git/forks/gpt-codebase-scanner/node_modules/openai/dist/common.js:149:22
    at /Users/alejandrosanchezgiraldo/git/forks/gpt-codebase-scanner/node_modules/openai/dist/api.js:1783:123

Node.js v17.9.1
```

**Comment by michaelKurowski** [comment]
Please try it on 19, the error might throw because your Node doesn't support the fetch API.

I've also added a note in the README regarding the costs of usage, please check it out if you want to use it:
https://github.com/michaelKurowski/gpt-codebase-scanner#costs

**Comment by michaelKurowski** [comment]
Feel free to reopen if you still experience the issue
